<?php defined('BLUDIT') or die('Maigewan CMS.'); ?>
{
    "2222222222222222": {
        "title": "2222222222222222",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2025-10-16 22:02:07",
        "dateModified": "",
        "position": 2,
        "coverImage": "",
        "category": "",
        "md5file": "559ed1bedd589668e00a61146f6097f7",
        "uuid": "458e913ade6f43caec5e47a29e6c73e4",
        "allowComments": true,
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false,
        "custom": [
            false
        ]
    },
    "create-your-own-content": {
        "title": "Create your own content",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2025-10-16 19:42:10",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "f4d8407a590b905129a8d40fce1aa37d",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "set-up-your-new-site": {
        "title": "Set up your new site",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2025-10-16 19:41:10",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "21f9511584d5d9c7bb8d12d3a3d6faf5",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "follow-bludit": {
        "title": "Follow Bludit",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2025-10-16 19:40:10",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "388b543dfe48ed4898332801eb49ae60",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "about": {
        "title": "About",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "static",
        "date": "2025-10-16 19:39:10",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "799c77771a5fbe086aba47231c661451",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}