<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "站点2",
    "slogan": "\u6b22\u8fce\u4f7f\u7528Bludit",
    "description": "Congratulations you have successfully installed your**Bludit**",
    "footer": "Copyright \u00a9 2025",
    "itemsPerPage": 6,
    "language": "zh_CN",
    "locale": "zh_CN",
    "timezone": "Asia\/Shanghai",
    "theme": "alternative",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "https:\/\/wiiwedding.com",
    "emailFrom": "no-reply@wiiwedding.com",
    "orderBy": "date",
    "currentBuild": "0",
    "twitter": "https:\/\/twitter.com\/bludit",
    "facebook": "https:\/\/www.facebook.com\/bluditcms",
    "codepen": "",
    "github": "https:\/\/github.com\/bludit",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false
}