<?php defined('BLUDIT') or die('Maigewan CMS.'); ?>
{
    "title": "\u7ad9\u70b9111111111",
    "slogan": "\u6b22\u8fce\u4f7f\u7528Bludit",
    "description": "\u6211\u662f\u4e00\u6bb5\u63cf\u8ff0\u5440!!!!||||",
    "footer": "Copyright \u00a9 2025",
    "primaryKeyword": "\u5a5a\u5e86\u670d\u52a122222",
    "itemsPerPage": 6,
    "language": "zh_CN",
    "locale": "zh_CN",
    "timezone": "Asia\/Shanghai",
    "theme": "fsblogx",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "https:\/\/wiiwedding.com",
    "emailFrom": "no-reply@wiiwedding.com",
    "orderBy": "date",
    "currentBuild": 20240806,
    "twitter": "https:\/\/twitter.com\/bludit",
    "facebook": "https:\/\/www.facebook.com\/bluditcms",
    "codepen": "",
    "github": "https:\/\/github.com\/bludit",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "mastodon": "",
    "dribbble": "",
    "vk": "",
    "thumbnailWidth": 400,
    "thumbnailHeight": 400,
    "thumbnailQuality": 100,
    "markdownParser": true,
    "customFields": "[]"
}